# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
import numpy as np
arr=np.array([0,2,3,4,5])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int32


# 2. Given a NumPy array 'arr', check if its data type is float64. 


In [3]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


#  3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [4]:
arr=np.array([1+3.j,2+4.j,5+6.j])
print(arr.dtype)

complex128


# 4.  Convert an existing NumPy array 'arr' of integers to float32 data type

In [8]:
arr = np.array([1, 2, 3])
arr_f=arr.astype(np.float32)
arr_f

array([1., 2., 3.], dtype=float32)

#  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [4]:
import numpy as np
arr=np.array([1.5,2.6,3.7])
print(arr.dtype)

arr_f=arr.astype(np.float32)
print(arr_f.dtype)

float64
float32


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [9]:
def array_attribtes(arr):
    shape=arr.shape
    size=arr.size
    datype=arr.dtype
    return shape,size,datype

arr=np.array([1,2,3])
print(array_attribtes(arr))
    

((3,), 3, dtype('int32'))


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [5]:
import numpy as np
def array_dim(arr):
    dim=arr.shape
    return dim
arr=np.array([[1,2,3],[1,2,3]])
print(array_dim(arr))

(2, 3)


# 8. design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [3]:
def item_size_info(arr):
    item_size=arr.itemsize
    total_size=arr.nbytes
    return item_size,total_size

arr=np.array([1,2,3])
print(item_size_info(arr))

(4, 12)


 # 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [7]:
import numpy as np
def strides_info(arr):
    stride_info=arr.strides
    return stride_info
arr=np.array([1,5,4])
print(strides_info(arr))

(4,)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array

In [8]:
def shape_stride_relationship(arr):
    arr_strides=arr.strides
    arr_shape=arr.shape
    return arr_strides,arr_shape
arr=np.array([1,2,3],[4,5,6])
print(shape_stride_relationship(arr))

((4,), (3,))


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [10]:
def create_zeros_array(n):
    zeros_array=np.zeros(n)
    return zeros_array
n=int(input("enter the num : "))
print("array =",create_zeros_array(n))   

enter the num : 5
array = [0. 0. 0. 0. 0.]


#  12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D  NumPy array filled with ones of size `rows x cols`.

In [15]:
def create_ones_matrix(rows,cols):
    ones_array=np.array([np.ones(shape=rows),np.ones(shape=cols)])
    return ones_array
rows=int(input("enter the rows"))
cols=int(input("enter the col"))
print("array = ",create_ones_matrix(rows,cols))

enter the rows5
enter the col5
array =  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and  creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`

In [19]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

arr = generate_range_array(1, 10, 2)
print(arr)

[1 3 5 7 9]


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as  arguments and generates a NumPy array with num equally spaced values between `start` and `stop`  (inclusive).

In [21]:
def generate_linear_space(start,stop,num): # two floats start, stop, and an integer num
    return np.linspace(start,stop,num)

arr=generate_linear_space(1.0,10.0,5)
print(arr)
    

[ 1.    3.25  5.5   7.75 10.  ]


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square  identity matrix of size `n x n` using `numpy.eye`.

In [22]:
def create_identity_matrix(n):
    return np.eye(n)
arr=create_identity_matrix(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 16. Write a function that takes a Python list and converts it into a NumPy array

In [23]:
def create_array(l1):
    return np.array(l1)
l1=[1,2,2,4]
arr=create_array(l1)
arr


array([1, 2, 2, 4])

# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


In [24]:
arr=np.array([1,2,6])
print(arr)
arr_view=arr.view()
print(arr_view)

[1 2 6]
[1 2 6]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [26]:
def concatenates_array(arrr1,arr2):
    conc_array=np.concatenate((arr1,arr2),axis=0)
    return conc_array 
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
concatenates_array(arr1,arr2)


array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

#  19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

In [30]:
def concatenates_array(arrr1,arr2):
    conc_array=np.concatenate((arr1,arr2),axis=1)
    return conc_array 
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
concatenates_array(arr1,arr2)


array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

#  20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [31]:
def vertical_stack_arrays(arr_list):
    return np.vstack(arr_list)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

result = vertical_stack_arrays([arr1, arr2, arr3])
print("Vertically Stacked Array:\n", result)

Vertically Stacked Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)  with a given step size.

In [1]:
import numpy as np

def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)  # Adding 1 to stop to make it inclusive

arr = create_range_array(1, 10, 2)
print(arr)  # Output: [ 1  3  5  7  9]


[1 3 5 7 9]


#  22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [2]:
def create_range_array(start,stop,step):
    return np.linspace(start,stop+1,step)
arr=create_range_array(0,1,5)
arr

array([0. , 0.5, 1. , 1.5, 2. ])

# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and  1000 (inclusive).

In [4]:
def create_range_array(start,stop,step):
    return np.logspace(start,stop+1,step)
arr=create_range_array(0,100,5)
arr

array([1.00000000e+000, 1.77827941e+025, 3.16227766e+050, 5.62341325e+075,
       1.00000000e+101])

# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values  are random integers between 1 and 100.

In [39]:
import pandas as pd
arr1=np.random.randint(1,100,size=(5,3),dtype='int')
df=pd.DataFrame(arr1,columns=["A",'B','C'])
df

A   B   C
0  90  75  22
1  81  33  53
2  41  51  22
3   1  11  93
4  59  36  73

# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column  with zeros. Use NumPy operations within the Pandas DataFrame.

In [11]:
import pandas as pd
import numpy as np

def replaces_all_negative(df,col_name):
    df[col_name]=np.where(df[col_name]<0,0,df[col_name])
    return df
data={'A':[1,2,70,-5,5,-8],'B':[4,-40,5,-45,0,-8]}
df=pd.DataFrame(data)
print("oroginal data: \n",df)
print("modified data:\n",replaces_all_negative(df,'A'))

oroginal data: 
     A   B
0   1   4
1   2 -40
2  70   5
3  -5 -45
4   5   0
5  -8  -8
modified data:
     A   B
0   1   4
1   2 -40
2  70   5
3   0 -45
4   5   0
5   0  -8


# 26. Access the 3rd element from the given NumPy array.

In [12]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

#  27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [15]:
arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

arr_2d[1][2]

6

#  28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [16]:
 arr = np.array([3, 8, 2, 10, 5, 7])

filtered_arr = arr[arr > 5]

print(filtered_arr)  


[ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [17]:
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

 # 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [24]:
arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array

In [1]:
import numpy as np

def extract_elements(arr, indices):
    return arr[indices[:, 0], indices[:, 1]]

arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

indices = np.array([[0, 1], [2, 2], [1, 0]]) 

result = extract_elements(arr, indices)
print(result)  


[20 90 40]


# 32.Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [2]:
def filters_elements(arr,threshold):
    return arr[arr>threshold]
arr = np.array([10, 25, 5, 40, 30, 15])
threshold = 20

result = filters_elements(arr, threshold)
print(result)  

[25 40 30]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [3]:
def extract_elements_3d(arr, x, y, z):
    return arr[x, y, z]  

arr = np.array([[[  1,  2,  3], 
                  [  4,  5,  6]], 

                 [[  7,  8,  9], 
                  [ 10, 11, 12]]])

x_idx = np.array([0, 1, 1])  
y_idx = np.array([1, 0, 1])
z_idx = np.array([2, 1, 0])

result = extract_elements_3d(arr, x_idx, y_idx, z_idx)
print(result) 

[ 6  8 10]


# 34.Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [6]:
def filters_elements(arr,threshold1,threshold2):
    return arr[(arr>threshold1)& (arr>threshold2)]
arr = np.array([10, 25, 5, 40, 30, 15])
threshold1 = 10
threshold2=20

result = filters_elements(arr, threshold1,threshold2)
print(result)  

[25 40 30]


# 35.Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [7]:
def extract_elements_2d(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]  

arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

row_indices = np.array([0, 2, 1])
col_indices = np.array([1, 2, 0])

result = extract_elements_2d(arr, row_indices, col_indices)
print(result)  

[20 90 40]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [8]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

# Add scalar value 5 using broadcasting
result = arr + 5

print(result)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [11]:
arr1=np.array([[10,20,30]])
arr2 = np.array([[1, 2, 3,4], 
                [4, 5, 6,5], 
                [7, 8, 9,6]])
re_arr=arr1.T
result=arr2*re_arr
print(result)

[[ 10  20  30  40]
 [ 80 100 120 100]
 [210 240 270 180]]


# 38.  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [15]:
arr1=np.array([10,20,30,40])
arr2 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9],
                [10,11,12]])
t_arr1=arr1.reshape(4,1)
sum=t_arr1+arr2
print(sum)

[[11 12 13]
 [24 25 26]
 [37 38 39]
 [50 51 52]]


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [21]:
arr1=np.array([[3],
               [4],
               [5]])
arr2=np.array([[1,2,3]])
add=arr1+arr2
print(add)

[[4 5 6]
 [5 6 7]
 [6 7 8]]


# 40.  Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [25]:
arr1 = np.array([[1, 2, 3], 
                 [4, 5, 6]])  

arr2 = np.array([[4, 5], 
                 [6, 7]])  


arr2_reshaped = arr2[:, 0:1]  


result = arr1 * arr2_reshaped 

print(arr2_reshaped)
print(result)


[[4]
 [6]]
[[ 4  8 12]
 [24 30 36]]


# 41.Calculate column wise mean for the given array:

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

column_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_mean)

Column-wise mean: [2.5 3.5 4.5]


# 42.Find maximum value in each row of the given array:

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max=np.max(arr,axis=1)
print("row-wise max:", row_max)

row-wise max: [3 6]


# 43. For the given array, find indices of maximum value in each column.

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
print("Indices of maximum values in each column:", max_indices)

Indices of maximum values in each column: [1 1 1]


# 44.For the given array, apply custom function to calculate moving sum along rows.

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
sum=np.sum(arr,axis=1)
print(sum)

[ 6 15]


# 45. In the given array, check if all elements in each column are even.

In [32]:
arr = np.array([[2, 4, 6], [3, 5, 7]])

all_even_columns = np.all(arr % 2 == 0, axis=0)

print("Are all elements even in each column?", all_even_columns)

Are all elements even in each column? [False False False]


# 46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

In [36]:
original_array = np.array([1, 2, 3, 4, 5, 6])
reshape_array=original_array.reshape(2,3)
print(reshape_array)

[[1 2 3]
 [4 5 6]]


# 47. Create a function that takes a matrix as input and returns the flattened array.

In [38]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flattend_array(matrix):
    return matrix.ravel() 
print(flattend_array(input_matrix))

[1 2 3 4 5 6]


# 48. Write a function that concatenates two given arrays along a specified axis.

In [40]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concat_array(arr1,arr2):
    return np.concatenate((arr1,arr2),axis=0)

print(concat_array(array1,array2))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# 49. Create a function that splits an array into multiple sub-arrays along a specified axis

In [45]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def splits_array(arr,num_splits, axis=0):
    return np.array_split(arr,num_splits, axis=axis)
    
split_arrays = splits_array(original_array, 2, axis=1)

for i, subarray in enumerate(split_arrays):
    print(f"Sub-array {i+1}:\n", subarray)

Sub-array 1:
 [[1 2]
 [4 5]
 [7 8]]
Sub-array 2:
 [[3]
 [6]
 [9]]


# 50.  Write a function that inserts and then deletes elements from a given array at specified indices.

In [46]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


def modify_array(arr, insert_indices, insert_values, delete_indices):
    modified_array = np.insert(arr, insert_indices, insert_values)
    modified_array = np.delete(modified_array, delete_indices)

    return modified_array


result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified Array:", result_array)


Modified Array: [ 1 10  4 11  5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [48]:
arr1=np.random.randint(1,11,size=10)
arr2=np.arange(1,11)

sum=arr1+arr2
print(sum)

[ 4  8  6 12 14 10 15 17 17 17]


# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise. 

In [54]:
arr1=np.arange(10,1,-1)
arr2=np.arange(1,10)
sub=arr1-arr2
print(sub)

[ 9  7  5  3  1 -1 -3 -5 -7]


# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [55]:
arr1=np.random.randint(1,11,size=5)
arr2=np.arange(1,6)

mul=arr1*arr2
print(mul)

[ 7 16 30  4 25]


# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [58]:
arr1=np.arange(2,11,2)
arr2=np.arange(1,6)

div=arr1/arr2
print(div)

[2. 2. 2. 2. 2.]


# 55.  Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [59]:
arr1=np.arange(1,6)
arr_rev=np.arange(6,1,-1)

pow=arr_rev**arr1
print(pow)

[ 6 25 64 81 32]


# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [60]:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
import numpy as np

def count_substring(arr, substring):
    return np.char.count(arr, substring)

substring = "hello"
counts = count_substring(arr, substring)

print("Array of Strings:", arr)
print(f"Occurrences of '{substring}':", counts)


Array of Strings: ['hello' 'world' 'hello' 'numpy' 'hello']
Occurrences of 'hello': [1 0 1 0 1]


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.


In [63]:
import numpy as np

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

upper_char = np.array([''.join([char for char in word if char.isupper()]) for word in arr])

print("Original Array:", arr)
print("Uppercase Characters:", upper_char)

Original Array: ['Hello' 'World' 'OpenAI' 'GPT']
Uppercase Characters: ['H' 'W' 'OAI' 'GPT']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [2]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
updated_arr = replace_substring(arr, "apple", "mango")

print("Original Array:", arr)
print("Updated Array:", updated_arr)



Original Array: ['apple' 'banana' 'grape' 'pineapple']
Updated Array: ['mango' 'banana' 'grape' 'pinemango']


# 59. Write a function that concatenates strings in a NumPy array element-wise.

In [3]:
def concatenate_arrays(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_arrays(arr1, arr2)

print("Concatenated Array:", result)

Concatenated Array: ['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.

In [4]:
import numpy as np

def longest_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
max_length = longest_string_length(arr)

print("Length of the longest string:", max_length)


Length of the longest string: 9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [5]:
dataset = np.random.randint(1, 1001, size=100)

mean_value = np.mean(dataset)
median_value = np.median(dataset)
variance_value = np.var(dataset)
std_deviation_value = np.std(dataset)

print("Dataset:", dataset)
print("Mean:", mean_value)
print("Median:", median_value)
print("Variance:", variance_value)
print("Standard Deviation:", std_deviation_value)

Dataset: [145 951 842 589  42 399 801 917 672 228 272 816 822 787 347 670 123 311
 532 853 246 861 566 552 597 484 519 299 590 276  99 625 838 661 317 968
 136 798 741 160 694 180 260 852 625 528 599 725 250 887 601 974 750 199
 164 892 420 129 951 803 880 491 312 275 918  11 163 736 928 844 760  88
 925 590 502 318  81 725 877   6 211 508 987 994 963 840 242 844  63 546
 184 144 915 178 670  77 185 834 172 938]
Mean: 538.6
Median: 589.5
Variance: 92460.52000000002
Standard Deviation: 304.0732148677355


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [6]:
dataset = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)

Dataset: [ 60  75  70  22  47  86  20  56  72  50  66   3  47  70  48  64  24  96
  30  44  39  43   2  39  68  38  91  58  85   5  59  26  16  54  29  19
   6  27  25   8  44  57  10  18  12  58  50  32  32 100]
25th Percentile: 24.25
75th Percentile: 59.75


# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [8]:
arr1 = np.random.randint(1, 100, size=10)
arr2 = np.random.randint(1, 100, size=10)

correlation_matrix = np.corrcoef(arr1, arr2)


print("Array 1:", arr1)
print("Array 2:", arr2)
print("Correlation Coefficient Matrix:\n", correlation_matrix)

Array 1: [ 5 25 89 13 23 83 14 63 66 13]
Array 2: [17 15  9 72 50 88 50 33 56 88]
Correlation Coefficient Matrix:
 [[ 1.         -0.06671189]
 [-0.06671189  1.        ]]


# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [9]:
import numpy as np

matrix1 = np.random.randint(1, 10, size=(3, 2))
matrix2 = np.random.randint(1, 10, size=(2, 3))

result = np.dot(matrix1, matrix2)

# Print results
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result)


Matrix 1:
 [[6 5]
 [8 6]
 [5 8]]
Matrix 2:
 [[2 3 4]
 [5 1 4]]
Result of Matrix Multiplication:
 [[37 23 44]
 [46 30 56]
 [50 23 52]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [11]:
arr = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)  
percentile_90 = np.percentile(arr, 90)
first_quartile = np.percentile(arr, 25)
third_quartile = np.percentile(arr, 75)

print("Array:", arr)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (Q1):", first_quartile)
print("Third Quartile (Q3):", third_quartile)

Array: [709 828 412 960 136 454 673  23 108 111 154 384 289 998 603 544 525 268
 443 726 184 668 128 357 884 335 152 676 435 580 292 929  80 991 671 551
 617 513 311 181 401 813 634 277 296 355 955 159 105 221]
10th Percentile: 126.30000000000001
50th Percentile (Median): 423.5
90th Percentile: 888.5000000000001
First Quartile (Q1): 232.75
Third Quartile (Q3): 670.25


# 66. Create a NumPy array of integers and find the index of a specific element.

In [13]:
arr = np.array([10, 20, 30, 40, 50, 60])

element = 30
for i in range(len(arr)):
    if arr[i]==element:
        print(f"Index of element {element}:", i)
    


Index of element 30: 2


# 67. Generate a random NumPy array and sort it in ascending order.

In [14]:
arr = np.array([50, 20, 60, 40, 100, 70])
print("sorted array is : ",sorted(arr))


sorted array is :  [20, 40, 50, 60, 70, 100]


# 68. Filter elements >20  in the given NumPy array.

In [15]:
arr = np.array([12, 25, 6, 42, 8, 30])
for i in arr:
    if i>20:
        print(i)

25
42
30


# 69. Filter elements which are divisible by 3 from a given NumPy array.

In [16]:
arr = np.array([1, 5, 8, 12, 15])
for i in arr:
    if i%3==0:
        print(i)

12
15


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [17]:
arr = np.array([10, 20, 30, 40, 50])
for i in arr:
    if 20<=i<=40:
        print(i)

20
30
40


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [19]:
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

print("Array:", arr)
print("Byte Order:", byte_order)

Array: [1 2 3]
Byte Order: =


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [21]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(True)

print("Byte-swapped Array:", arr)

Byte-swapped Array: [16777216 33554432 50331648]


# 73. For the given NumPy array, swap its byte order without modifying the original array using`newbyteorder()`.

In [23]:
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.newbyteorder()

print("Original Array:", arr)
print("Byte-swapped Array:", swapped_arr)

Original Array: [1 2 3]
Byte-swapped Array: [16777216 33554432 50331648]


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using`newbyteorder()`.

In [24]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  
    swapped_arr = arr.newbyteorder()
else:
    swapped_arr = arr  

print("Original Array:", arr)
print("Byte-swapped Array:", swapped_arr)

Original Array: [1 2 3]
Byte-swapped Array: [16777216 33554432 50331648]


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`attribute `byteorder`.

In [25]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder == '=':  
    needs_swapping = False
else:
    needs_swapping = True

print("Array:", arr)
print("Byte Order:", arr.dtype.byteorder)
print("Needs Byte Swapping:", needs_swapping)

Array: [1 2 3]
Byte Order: =
Needs Byte Swapping: False


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [26]:
arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original Array (arr1):", arr1)
print("Modified Copy (copy_arr):", copy_arr)

if np.array_equal(arr1, copy_arr):
    print("Modification affected the original array.")
else:
    print("Modification did NOT affect the original array.")

Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy (copy_arr): [100   2   3   4   5   6   7   8   9  10]
Modification did NOT affect the original array.


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [27]:
matrix = np.random.randint(1, 100, size=(3, 3))

view_slice = matrix[:2, :2]  

view_slice[0, 0] = 999

print("Original Matrix after modifying view_slice:\n", matrix)
print("View Slice:\n", view_slice)

Original Matrix after modifying view_slice:
 [[999  42  78]
 [ 34  46  17]
 [ 69  50   4]]
View Slice:
 [[999  42]
 [ 34  46]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.


In [28]:
array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[:2, :]
view_b += 5

print("Original Array after modifying view_b:\n", array_a)

Original Array after modifying view_b:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if itreflects changes in the original `orig_array`.


In [29]:
orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)
reshaped_view[1, 0] = 999

print("Original Array after modifying reshaped_view:\n", orig_array)

Original Array after modifying reshaped_view:
 [[  1   2 999   4]
 [  5   6   7   8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [30]:
data = np.random.randint(1, 20, (3, 4))

data_copy = data[data > 5].copy()
data_copy[0] = 999


print("Original Array:\n", data)
print("Modified Copy:\n", data_copy)


Original Array:
 [[10  9 17  3]
 [11  2 17  6]
 [10  4 12 16]]
Modified Copy:
 [999   9  17  11  17   6  10  12  16]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [31]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

add_result = A + B
sub_result = A - B

print("Addition:\n", add_result)
print("Subtraction:\n", sub_result)

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [32]:
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

result = np.dot(C, D)

print("Matrix Multiplication Result:\n", result)

Matrix Multiplication Result:
 [[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


# 83. Create a matrix `E` and find its transpose.

In [33]:
E = np.array([[1, 2, 3], [4, 5, 6]])

E_transpose = E.T

print("Original Matrix:\n", E)
print("Transposed Matrix:\n", E_transpose)


Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


# 84. Generate a square matrix `F` and compute its determinant.


In [34]:
F = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
det_F = np.linalg.det(F)

print("Determinant of F:", det_F)


Determinant of F: -306.0


# 85. Create a square matrix `G` and find its inverse

In [35]:
G = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])

G_inverse = np.linalg.inv(G)

print("Inverse of G:\n", G_inverse)

Inverse of G:
 [[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]
