# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [2]:
import numpy as np
arr=np.array([0,2,3,4,5])
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int32


# 2. Given a NumPy array 'arr', check if its data type is float64. 


In [3]:
arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


#  3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [4]:
arr=np.array([1+3.j,2+4.j,5+6.j])
print(arr.dtype)

complex128


# 4.  Convert an existing NumPy array 'arr' of integers to float32 data type

In [8]:
arr = np.array([1, 2, 3])
arr_f=arr.astype(np.float32)
arr_f

array([1., 2., 3.], dtype=float32)

#  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [4]:
import numpy as np
arr=np.array([1.5,2.6,3.7])
print(arr.dtype)

arr_f=arr.astype(np.float32)
print(arr_f.dtype)

float64
float32


# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [9]:
def array_attribtes(arr):
    shape=arr.shape
    size=arr.size
    datype=arr.dtype
    return shape,size,datype

arr=np.array([1,2,3])
print(array_attribtes(arr))
    

((3,), 3, dtype('int32'))


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [5]:
import numpy as np
def array_dim(arr):
    dim=arr.shape
    return dim
arr=np.array([[1,2,3],[1,2,3]])
print(array_dim(arr))

(2, 3)


# 8. design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [3]:
def item_size_info(arr):
    item_size=arr.itemsize
    total_size=arr.nbytes
    return item_size,total_size

arr=np.array([1,2,3])
print(item_size_info(arr))

(4, 12)


 # 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [7]:
import numpy as np
def strides_info(arr):
    stride_info=arr.strides
    return stride_info
arr=np.array([1,5,4])
print(strides_info(arr))

(4,)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array

In [8]:
def shape_stride_relationship(arr):
    arr_strides=arr.strides
    arr_shape=arr.shape
    return arr_strides,arr_shape
arr=np.array([1,2,3],[4,5,6])
print(shape_stride_relationship(arr))

((4,), (3,))


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [10]:
def create_zeros_array(n):
    zeros_array=np.zeros(n)
    return zeros_array
n=int(input("enter the num : "))
print("array =",create_zeros_array(n))   

enter the num : 5
array = [0. 0. 0. 0. 0.]


#  12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D  NumPy array filled with ones of size `rows x cols`.

In [15]:
def create_ones_matrix(rows,cols):
    ones_array=np.array([np.ones(shape=rows),np.ones(shape=cols)])
    return ones_array
rows=int(input("enter the rows"))
cols=int(input("enter the col"))
print("array = ",create_ones_matrix(rows,cols))

enter the rows5
enter the col5
array =  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and  creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`

In [19]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

arr = generate_range_array(1, 10, 2)
print(arr)

[1 3 5 7 9]


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as  arguments and generates a NumPy array with num equally spaced values between `start` and `stop`  (inclusive).

In [21]:
def generate_linear_space(start,stop,num): # two floats start, stop, and an integer num
    return np.linspace(start,stop,num)

arr=generate_linear_space(1.0,10.0,5)
print(arr)
    

[ 1.    3.25  5.5   7.75 10.  ]


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square  identity matrix of size `n x n` using `numpy.eye`.

In [22]:
def create_identity_matrix(n):
    return np.eye(n)
arr=create_identity_matrix(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 16. Write a function that takes a Python list and converts it into a NumPy array

In [23]:
def create_array(l1):
    return np.array(l1)
l1=[1,2,2,4]
arr=create_array(l1)
arr


array([1, 2, 2, 4])

# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.


In [24]:
arr=np.array([1,2,6])
print(arr)
arr_view=arr.view()
print(arr_view)

[1 2 6]
[1 2 6]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [26]:
def concatenates_array(arrr1,arr2):
    conc_array=np.concatenate((arr1,arr2),axis=0)
    return conc_array 
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
concatenates_array(arr1,arr2)


array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

#  19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

In [30]:
def concatenates_array(arrr1,arr2):
    conc_array=np.concatenate((arr1,arr2),axis=1)
    return conc_array 
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[7,8,9]])
concatenates_array(arr1,arr2)


array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9]])

#  20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [31]:
def vertical_stack_arrays(arr_list):
    return np.vstack(arr_list)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

result = vertical_stack_arrays([arr1, arr2, arr3])
print("Vertically Stacked Array:\n", result)

Vertically Stacked Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)  with a given step size.

In [1]:
import numpy as np

def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)  # Adding 1 to stop to make it inclusive

arr = create_range_array(1, 10, 2)
print(arr)  # Output: [ 1  3  5  7  9]


[1 3 5 7 9]


#  22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [2]:
def create_range_array(start,stop,step):
    return np.linspace(start,stop+1,step)
arr=create_range_array(0,1,5)
arr

array([0. , 0.5, 1. , 1.5, 2. ])

# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and  1000 (inclusive).

In [4]:
def create_range_array(start,stop,step):
    return np.logspace(start,stop+1,step)
arr=create_range_array(0,100,5)
arr

array([1.00000000e+000, 1.77827941e+025, 3.16227766e+050, 5.62341325e+075,
       1.00000000e+101])

# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values  are random integers between 1 and 100.

In [39]:
import pandas as pd
arr1=np.random.randint(1,100,size=(5,3),dtype='int')
df=pd.DataFrame(arr1,columns=["A",'B','C'])
df

A   B   C
0  90  75  22
1  81  33  53
2  41  51  22
3   1  11  93
4  59  36  73

# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column  with zeros. Use NumPy operations within the Pandas DataFrame.

In [11]:
import pandas as pd
import numpy as np

def replaces_all_negative(df,col_name):
    df[col_name]=np.where(df[col_name]<0,0,df[col_name])
    return df
data={'A':[1,2,70,-5,5,-8],'B':[4,-40,5,-45,0,-8]}
df=pd.DataFrame(data)
print("oroginal data: \n",df)
print("modified data:\n",replaces_all_negative(df,'A'))

oroginal data: 
     A   B
0   1   4
1   2 -40
2  70   5
3  -5 -45
4   5   0
5  -8  -8
modified data:
     A   B
0   1   4
1   2 -40
2  70   5
3   0 -45
4   5   0
5   0  -8


# 26. Access the 3rd element from the given NumPy array.

In [12]:
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

#  27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [15]:
arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

arr_2d[1][2]

6

#  28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [16]:
 arr = np.array([3, 8, 2, 10, 5, 7])

filtered_arr = arr[arr > 5]

print(filtered_arr)  


[ 8 10  7]


# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

In [17]:
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

 # 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [24]:
arr_2d = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])